server:
  port: 8080
spring:
  messages:
    #i18n配置文件路径
    basename: message/validation
    encoding: UTF-8
knife4j:
  enable: true
  documents:
    - group: Test Group
      name: My Documents
      locations:
  setting:
    # default lang
#    language: en-US
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT | [Java 全栈](https://pdai.tech)
    # header
    enableHomeCustom: true
    homeCustomLocation:
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models
